# Accuracy across 10 runs: 0.6994 ± 0.004005
version: 0.0.2
pipeline_name: nodepred
pipeline_mode: train
device: cuda:0
data:
  name: citeseer
model:
  name: sage
  embed_size: -1              # The dimension of created embedding table. -1 means using original node embedding
  hidden_size: 16             # Hidden size.
  num_layers: 2               # Number of layers.
  activation: relu
  dropout: 0.5                # Dropout rate.
  aggregator_type: gcn        # Aggregator type to use (``mean``, ``gcn``, ``pool``, ``lstm``).
general_pipeline:
  early_stop:
    patience: 100             # Steps before early stop
    checkpoint_path: checkpoint.pth # Early stop checkpoint model file path
  num_epochs: 200             # Number of training epochs
  eval_period: 5              # Interval epochs between evaluations
  optimizer:
    name: Adam
    lr: 0.01
    weight_decay: 0.0005
  loss: CrossEntropyLoss
  save_path: "results"        # Directory to save the experiment results
  num_runs: 10                # Number of experiments to run
