"""Constants"""
GET_ATTR = "get_attr"
CALL_MODULE = "call_module"
CALL_FUNCTION = "call_function"
CALL_METHOD = "call_method"
PLACEHOLDER = "placeholder"
OUTPUT = "output"

TENSOR_DATA = "TensorData"
DGL_GRAPH_DATA = "DGLGraphData"
DGL_GRAPH = "DGLGraph"
MASSAGE_PASSING = "MessagePassing"
