apiVersion: "kubeflow.org/v1"
kind: "TFJob"
metadata:
  name: "dgl-dist-kvstore-test"
spec:
  tfReplicaSpecs:
    PS:
      replicas: 2
      restartPolicy: Never
      template:
        metadata:
          labels:
            dgl-test: dist
        spec:
          containers:
            - name: tensorflow
              image: public.ecr.aws/s1o7b3d9/benchmakrk_pyg_dgl:cu111_torch181_pyg170
              ports:
              - containerPort: 30051
                name: dist-port1
              - containerPort: 30050
                name: dist-port2
              args: 
              - "bash"
              - "-c"
              - |
                echo $TF_CONFIG
                sleep 10s
                git clone https://github.com/dmlc/dgl.git
                cd dgl/benchmarks/distributed
                python parse_tf_config.py
                cat ip_config.txt
                export MACHINE_ID=$(cat machine_id.txt)
                echo $MACHINE_ID
                export PYTHONUNBUFFERED=1
                pip install --pre dgl -f https://data.dgl.ai/wheels-test/repo.html
                python -c "import dgl"
                python3 benchmark_kvstore.py.py --server_id $MACHINE_ID --machine_id $MACHINE_ID & python3 benchmark_kvstore.py.py --machine_id $MACHINE_ID
          affinity: # Specify instance type and seperate two pods on to two machines
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: beta.kubernetes.io/instance-type
                    operator: In
                    values:
                    - m5n.24xlarge
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                    - key: dgl-test
                      operator: In
                      values:
                      - dist
                  topologyKey: kubernetes.io/hostname          
          tolerations:
            - key: dgl.ai/dedicated
              operator: "Exists"
              effect: "NoSchedule"
          # hostNetwork: true
          # hostPorts:
          # - min: 0
          #   max: 65535
          # dnsPolicy: ClusterFirstWithHostNet
    # Worker:
    #   replicas: 4
    #   restartPolicy: Never
    #   template:
    #     spec:
    #       containers:
    #         - name: tensorflow
    #           image: kubeflow/tf-dist-mnist-test:1.0