package:
  name: dgllife{{ environ.get('APP_PACKAGE_SUFFIX', '') }}
  version: "0.2.2"

source:
  url: https://files.pythonhosted.org/packages/19/e7/7d9890c7ddb303613f8a9c0bafafa40239e65f9c0698e699f19f577412fc/dgllife-0.2.2.tar.gz
  sha256: 812a93d54cd5c049a7368aae01d53b5a4a12ca2d0e4e57d74fa4a844a1c01d92

requirements:
  build:
    - python {{ python }}
    - setuptools
    - cmake
    - git
    - cython
  run:
    - python
    - requests
    - scikit-learn
    - pandas
    - tqdm
    - numpy
    - scipy
    - networkx

about:
  license: Apache