package:
  name: dgl{{ environ.get('DGL_PACKAGE_SUFFIX', '') }}
  version: "0.3.1"

source:
  git_rev: 0.3.x
  git_url: https://github.com/dmlc/dgl.git

requirements:
  build:
    - python {{ python }}
    - setuptools
    - cmake
    - git
    - cython
  run:
    - python
    - numpy
    - scipy
    - networkx

build:
  script_env:
    - USE_CUDA
    - CUDA_VER

about:
  home: https://github.com/dmlc/dgl.git
  license_file: {{ environ.get('SRC_DIR') }}/LICENSE
  license: Apache
