package:
  name: dgl{{ environ.get('DGL_PACKAGE_SUFFIX', '') }}
  version: 2.5{{ environ.get('DGL_VERSION_SUFFIX', '') }}

source:
  git_rev: {{ environ.get('DGL_RELEASE_BRANCH', 'master') }}
  git_url: https://github.com/dmlc/dgl.git

requirements:
  build:
    - python {{ python }}
    - setuptools
    - cmake
    - git
    - cython
  run:
    - python
    - numpy
    - scipy
    - networkx
    - requests
    - tqdm
    - psutil

build:
  script_env:
    - USE_CUDA
    - CUDA_VER
    - CACHEDIR
    - DGL_VERSION_SUFFIX

about:
  home: https://github.com/dmlc/dgl.git
  license_file: {{ environ.get('SRC_DIR') }}/LICENSE
  license: Apache
